### PR TITLE
Fix styling on devise form errors

### LINKED ISSUE #45: Fix styling on devise form errors
In commit c26c8, I added an errors partial for form errors and styled it, but I forgot that Devise uses `#error_explanation` to wrap it's form errors. We should add styling back in for these divs (e.g. try to update an user's password, but don't enter the current password), and keep the new styling we have for our errors (e.g. when creating a "deed" enter zero for both trash bags and miles).

### PR DESCRIPTION
**Pull request by sundus-y**
* Resolves #45 
* Changes the error_explanation class for forms from being a class to an
  id since Devise already uses #error_explanation.
* Also updates the _error.scss to use the id instead of the class.

### CODE REVIEW

**Comment by crawfoal** [comment]
Thanks!

Can you look at the difference in styling between Devise's errors and the errors that this app generates? If you trigger an error on the user registration form, and then compare that style to an error on the deed form, you'll see that Devise is using the h2 heading level. I think that looks a little funny because the form's heading is h2 as well. I've worked around this in the past by just chaging the font size of the heading in Devise's errors to be equal to the h3 font size. In this app h3's have a font size of `modular-scale(1)`.

**Comment by sundus-y** [comment]
Actually, having the h2 twice as the form header and also as the error message header might not be a good design in regards to accessibility. So I will see if I can actually override the Devise error message rendering to conform to [w3-Accessibility Standard](https://www.w3.org/WAI/tutorials/page-structure/headings/).

**Comment by crawfoal** [comment]
That sounds great, thanks!

**Comment by sundus-y** [comment]
I have made the changes needed. It's ready for another review.

File: app/helpers/devise_helper.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+    end
+  end
+
+  def full_messages_in_li
+    resource.errors.full_messages.map do |msg|
+      content_tag(:li, msg)
+    end
+  end
+
+  def formatted_sentence
```
Comment (crawfoal) [inline app/helpers/devise_helper.rb]: I think it would be easier to follow the code if we named this something like `error_header` or `error_intro`.

File: app/helpers/devise_helper.rb [hunk 2]
```diff
@@ -0,0 +1,21 @@
+module DeviseHelper
+  def devise_error_messages!
+    return '' if resource.errors.empty?
+    content_tag(:div, id: 'error_explanation') do
+      safe_join [content_tag(:h3, formatted_sentence),
+                 content_tag(:ul, safe_join(full_messages_in_li))]
+    end
+  end
+
+  def full_messages_in_li
```
Comment (crawfoal) [inline app/helpers/devise_helper.rb]: Should this and the next method be private?

File: spec/helpers/devise_helper_spec.rb [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+          )
+        allow(helper).to receive_message_chain('resource.errors.full_messages')\
+          .and_return(
+            ['Error Message 1', 'Error Message 2']
+          )
+        allow(helper).to \
+          receive_message_chain('resource.class.model_name.human')
+          .and_return('ModelName')
+        msg = '<h3>2 errors prohibited this modelname from being saved:</h3>'
+        expect(helper.devise_error_messages!).to include(msg)
```
Comment (crawfoal) [inline spec/helpers/devise_helper_spec.rb]: `msg` includes "prohibited this" and "from being saved", which this test shouldn't really care about because those parts of the error message aren't affected by the logic in the `devise_error_messages!` method.

It looks like `devise_error_messages!` does three or four things:
  1. Build the header
  2. Build the list of error messages
  3. Put 1 and 2 together and escape everything

If the spec(s) for this helper method looked for things like '\<h3>', 'Error Message 1', 'id="error_explanation"`, the scope of the spec(s) would more closely match the function they're testing.

File: spec/helpers/devise_helper_spec.rb [hunk 4]
```diff
@@ -0,0 +1,23 @@
+require 'rails_helper'
+
+RSpec.describe DeviseHelper, type: :helper do
+  describe '#devise_error_messages!' do
+    it 'returns div error_messages with h3 header' do
```
Comment (crawfoal) [inline spec/helpers/devise_helper_spec.rb]: Do you mean "error_explanation" rather than "error_messages"?

File: app/helpers/devise_helper.rb (hunk 2 above)
Comment (sundus-y) [reply app/helpers/devise_helper.rb]: Done

File: app/helpers/devise_helper.rb (hunk 1 above)
Comment (sundus-y) [reply app/helpers/devise_helper.rb]: Done

File: spec/helpers/devise_helper_spec.rb (hunk 4 above)
Comment (sundus-y) [reply spec/helpers/devise_helper_spec.rb]: Ya, Done

File: spec/helpers/devise_helper_spec.rb (hunk 3 above)
Comment (sundus-y) [reply spec/helpers/devise_helper_spec.rb]: Done, added more test to match methods functionality.

**Comment by sundus-y** [comment]
All PR review questions have been addressed. It's ready for another round of review.

File: spec/helpers/devise_helper_spec.rb [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+          )
+        allow(helper).to \
+          receive_message_chain('resource.class.model_name.human')
+          .and_return('ModelName')
+      end
+    end
+
+    it 'returns h3 error message header' do
+      header = '<h3>2 errors prohibited this modelname from being saved:</h3>'
+      expect(helper.devise_error_messages!).to include(header)
```
Comment (crawfoal) [inline spec/helpers/devise_helper_spec.rb]: I like how you broke out multiple specs, I think that's a great idea. I think that this one needs a little more work, but the other two look great!

If someone were to go into the devise translations file (`config/locales/devise.en.yml`) and change the text that is used in the header (the string with key `devise.errors.not_saved`), then this spec would fail even though no functionality was actually broken. This is why I suggest that your expectation only asserts that `<h3>` is in there.

File: app/helpers/devise_helper.rb [hunk 6]
```diff
@@ -0,0 +1,23 @@
+module DeviseHelper
+  def devise_error_messages!
+    return '' if resource.errors.empty?
+    content_tag(:div, id: 'error_explanation') do
+      safe_join [content_tag(:h3, error_header),
```
Comment (crawfoal) [inline app/helpers/devise_helper.rb]: We should add another spec that asserts that the HTML is escaped so that we would catch a regression here.

File: spec/helpers/devise_helper_spec.rb (hunk 5 above)
Comment (sundus-y) [reply spec/helpers/devise_helper_spec.rb]: screen shot 2017-10-12 at 9 56 22 am
Sorry my editor was trying to be over helpful by resolving the I18n translation, I will update the spec.

**Comment by sundus-y** [comment]
@crawfoal have made all the needed updates. and wasn't this PR tagged as #hacktoberfest ?

**Comment by crawfoal** [comment]
Ya, the issue was labeled as Hacktoberfest - I've added the label to the PR

File: app/helpers/devise_helper.rb (hunk 6 above)
Comment (crawfoal) [reply app/helpers/devise_helper.rb]: I just realized that this call to `safe_join` is unnecessary - `content_tag` escapes html by default. The one on the next line is necessary.

Comment (sundus-y) [reply app/helpers/devise_helper.rb]: If I change the ```safe_join``` with a regular ```join```, the value returned will be a string that contains HTML but not marked as html safe. This will cause the string to be HTML escaped.

This is an example of what I would get if I were to change it:
```
<div id=\"error_explanation\">&lt;h3&gt;2 errors prohibited this modelname from being saved:&lt;/h3&...&lt;ul&gt;&lt;li&gt;Error Message 1&lt;/li&gt;&lt;li&gt;Error Message 2&lt;/li&gt;&lt;/ul&gt;</div>
```

Comment (crawfoal) [reply app/helpers/devise_helper.rb]: Huh, I thought I had tested that out before recommending that and found that the first wasn't necessary.

**Comment by crawfoal** [comment]
Thanks! Hope to see back with more PRs 🙂
